export const Data=[
    {
        id:1,
        name:"Mushroom",
        image:"assets/Mushroom.png",
        selected:false
    },
    {
        id:2,
        name:"Olive",
        image:"assets/Olive.png",
        selected:false
    },
    {
        id:3,
        name:"Corn",
        image:"assets/Corn.png",
        selected:false
    },
    {
        id:4,
        name:"Basil",
        image:`assets/Basil.png`,
        selected:false
    },
    {
        id:5,
        name:"Tomato",
        image:"assets/Tomato.png",
        selected:false
    },
    {
        id:6,
        name:"Cheese",
        image:"assets/BaseCheese.png",
        selected:false
    }
]